# Generated by Django 4.1 on 2022-08-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_alter_phone_invoice_alter_phone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.phone'),
        ),
        migrations.AddField(
            model_name='phone',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
