# Generated by Django 4.1 on 2022-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_phone_invoice_invoice_phone_id_phone_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(blank=True, choices=[('consideration', 'consideration'), ('in_progress', 'in progress'), ('done', 'done')], max_length=255, null=True),
        ),
    ]
